In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
data = pd.read_csv("/content/drive/MyDrive/final_dataset.csv")
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2342821 entries, 0 to 2342820
Data columns (total 15 columns):
 #   Column          Dtype
---  ------          -----
 0   Unnamed: 0      int64
 1   match_id        object
 2   shotX           float64
 3   shotY           float64
 4   quarter         object
 5   time_remaining  object
 6   player          object
 7   team            object
 8   made            bool
 9   shot_type       object
 10  distance        int64
 11  score           object
 12  opp             object
 13  status          object
 14  date            object
dtypes: bool(1), float64(2), int64(2), object(10)
memory usage: 252.5+ MB

In [3]:
data.head()

,Unnamed: 0,match_id,shotX,shotY,quarter,time_remaining,player,team,made,shot_type,distance,score,opp,status,date
0,0,200010310ATL,8.3,20.2,1st quarter,11:29.0,Baron Davis,CHH,False,2-pointer,22,0-2,'CHH',trails,10-31-2000
1,1,200010310ATL,35.9,15.8,1st quarter,10:41.0,Jamal Mashburn,CHH,False,2-pointer,16,0-2,'CHH',trails,10-31-2000
2,2,200010310ATL,24.0,5.0,1st quarter,10:38.0,Baron Davis,CHH,False,2-pointer,0,0-2,'CHH',trails,10-31-2000
3,3,200010310ATL,15.4,5.9,1st quarter,9:36.0,Elden Campbell,CHH,False,2-pointer,9,0-4,'CHH',trails,10-31-2000
4,4,200010310ATL,20.3,25.0,1st quarter,9:18.0,David Wesley,CHH,True,2-pointer,20,2-4,'CHH',trails,10-31-2000

## Data Cleaning & Preprocessing

In [4]:
#data['made']
#string_to_binary = {'True': "1", 'False': "0"}
#data['made'] = data['made'].map(string_to_binary)

In [5]:
data['match_id'] = data['match_id'].str[:-4]
data['quarter'] = data['quarter'].str[:1]
data['shot_type'] = data['shot_type'].str[:1]

In [6]:
data['match_id'] = pd.to_numeric(data['match_id']).astype('Int64')
data['quarter'] = pd.to_numeric(data['quarter']).astype('Int64')
data['shot_type'] = pd.to_numeric(data['shot_type']).astype('Int64')

In [7]:
string_to_binary = {'leads': "1", 'trails': "0"}
data['status'] = data['status'].map(string_to_binary)
data['status'] = pd.to_numeric(data['status']).astype('Int64')

In [8]:
data.head()

,Unnamed: 0,match_id,shotX,shotY,quarter,time_remaining,player,team,made,shot_type,distance,score,opp,status,date
0,0,20001031,8.3,20.2,1,11:29.0,Baron Davis,CHH,False,2,22,0-2,'CHH',0,10-31-2000
1,1,20001031,35.9,15.8,1,10:41.0,Jamal Mashburn,CHH,False,2,16,0-2,'CHH',0,10-31-2000
2,2,20001031,24.0,5.0,1,10:38.0,Baron Davis,CHH,False,2,0,0-2,'CHH',0,10-31-2000
3,3,20001031,15.4,5.9,1,9:36.0,Elden Campbell,CHH,False,2,9,0-4,'CHH',0,10-31-2000
4,4,20001031,20.3,25.0,1,9:18.0,David Wesley,CHH,True,2,20,2-4,'CHH',0,10-31-2000

In [9]:
columns_to_drop = ["Unnamed: 0","team","opp","score", "time_remaining","date"]
df = data.drop(columns=columns_to_drop, axis=1)
df['made'] = df['made'].map({True: 1, False: 0})
df['match_id'] = pd.to_numeric(df['match_id']).astype('Int64')

In [33]:
df.head()
# match_id	shotX	shotY	quarter	player	made	shot_type	distance	status	player_name
def historical_players(df, year=2010):
  # 20001031

  # Filter the DataFrame
  filtered_df = df[
      df['match_id'].astype(str).str.slice(start=0, stop=4).astype(int) <= year
  ]

  # Drop duplicate players
  unique_players_df = filtered_df.drop_duplicates(subset='player')

  # Extract the 'player' column if you just want the list of players
  unique_players = unique_players_df['player']

  return unique_players

def filter_players_by_retirement_year(df, year):
    # Convert match_id to year and check if any entry per player is after 'year'
    df['year'] = df['match_id'].astype(str).str.slice(start=0, stop=4).astype(int)

    # Group by player and find the maximum year they played
    max_years = df.groupby('player')['year'].max().reset_index()
    # Filter players whose maximum year is less than or equal to the specified year
    eligible_players = max_years[max_years['year'] == year]
    print(eligible_players)
    # # Filter the original dataframe to include only eligible players
    # filtered_df = df[df['player'].isin(eligible_players['player'])]

    # Optionally, drop the 'year' column if you added it only for this calculation
    filtered_df = filtered_df.drop(columns=['year'])

    return filtered_df

# historical_players(df=df)
filter_players_by_retirement_year(df, 2015)

Empty DataFrame
Columns: [player, year]
Index: []

Empty DataFrame
Columns: [match_id, shotX, shotY, quarter, player, made, shot_type, distance, status]
Index: []

In [ ]:
kljlk

## Data Filtering

In [ ]:
# Get user input for first name
first_name = input("Enter your first name: ")

# Get user input for last name
last_name = input("Enter your last name: ")

# Capitalize the first letter of each word
capitalized_first_name = first_name.title()
capitalized_last_name = last_name.title()

name = capitalized_first_name + " " + capitalized_last_name
print(name)

In [ ]:
# Create a new column with True/False indicating if the search value is present
df['player_name'] = df['player'].eq(name)

# Display the updated DataFrame
print(df['player_name'])

df['player_name'] = df['player_name'].astype(int)

cond2 = df['player_name'] == 1

In [ ]:
two_pt = input("Do you want 2-point shots? (y/n) ")
three_pt = input("Do you want 3-point shots? (y/n) ")

# Capitalize the first letter of each word
cap_two_pt = two_pt.title()
cap_three_pt = three_pt.title()
parity1 = True

if(cap_two_pt == 'Y' and cap_two_pt == 'Y'):
  print("No need to filter by point-shot")
  parity1 = False
elif(cap_two_pt == 'Y'):
  cond1 = df['shot_type'] == 2
elif(cap_three_pt == 'Y'):
  cond1 = df['shot_type'] == 3

In [ ]:
all_dates = input("Do you want all dates? (y/n) ")
cap_all_dates = all_dates.title()
parity1 = True

if(cap_all_dates == "N"):
  start_date = input("Give a start date (yyyymmdd)")
  end_date = input("Give an end date (yyyymmdd)")
  cond3 = (df['match_id'] >= start_date) & (df['match_id'] <= end_date)
else:
  print("All dates in dataset are included")
  parity2 = False

In [ ]:
filter_df = df[cond1]
if(parity1 == True):
  filter_df = filter_df[cond2]
if(parity2 == True):
  filter_df = filter_df[cond3]

In [ ]:
filter_df

## Data Modeling

In [ ]:
#filtered_df
from sklearn.cluster import DBSCAN
from sklearn.datasets import make_blobs
import matplotlib.pyplot as plt

# Generate some sample data (you can replace this with your dataset)
#X, _ = make_blobs(n_samples=300, centers=3, random_state=42)

# Apply DBSCAN
dbscan = DBSCAN(eps=0.5, min_samples=5)
labelss = dbscan.fit_predict(filtered_df)

# Plot the results
#plt.scatter(data[:, 0], X[:, 1], c=labels, cmap='viridis', s=50)
plt.scatter(filtered_df["X"], filtered_df["Y"], c=labelss, cmap='viridis', s=50)
plt.title('DBSCAN Clustering')
plt.xlabel('Feature 1')
plt.ylabel('Feature 2')
plt.show()

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.cluster import DBSCAN
from sklearn.datasets import make_blobs

# Generate synthetic data
#X, _ = make_blobs(n_samples=300, centers=3, random_state=42)
grouped_data = df.groupby('player')
# Apply DBSCAN
dbscan = DBSCAN(eps=5, min_samples=100)
labelss = dbscan.fit_predict(df)

# Plot the original data
#plt.scatter(df["X"], df["Y"], c='gray', label='Original Data', edgecolors='k')
#cat = pd.Categorical(df)
#print(cat)

## Data Visulization

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.cluster import DBSCAN
from sklearn.datasets import make_blobs

# Generate synthetic data
#X, _ = make_blobs(n_samples=300, centers=3, random_state=42)

# Apply DBSCAN
dbscan = DBSCAN(eps=5, min_samples=100)
labelss = dbscan.fit_predict(df)

# Plot the original data
plt.scatter(df["X"], df["Y"], c='gray', label='Original Data', edgecolors='k')

# Plot the clustered data using different colors for each cluster
unique_labels = np.unique(labelss)
for label in unique_labels:
    if label == -1:
        # Outliers (noise points) are red
        plt.scatter(X[labelss == label], Y[labelss == label], c='black', marker='x', label='Noise', s=50)
    else:
        # Inliers (clustered points) have different colors
        plt.scatter(X[labelss == label], Y[labelss == label], label=f'Cluster {label}', s=50)

plt.title('DBSCAN Clustering')
plt.xlabel('Feature 1')
plt.ylabel('Feature 2')
plt.legend()
plt.show()